weights: ./yolov5m.pt
cfg: ./models/yolov5m_class.yaml
data: ./data/class.yaml
hyp: ./data/hyp.scratch.yaml
epochs: 100
batch_size: 64
img_size:
- 480
- 480
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '1'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: expm
exist_ok: false
total_batch_size: 64
world_size: 1
global_rank: -1
save_dir: runs/train/expm6
